---
- import_playbook: gather_policy_info.yml

- hosts: all
  become: yes
  tasks:
    - name: Installing the OpenSCAP client
      yum:
        name: "rubygem-foreman_scap_client"
        enablerepo: "rhel-{{ ansible_distribution_major_version }}-server-satellite-tools-{{ satellite_version }}-rpms"
        state: present

    - name: Update /etc/foreman_scap_client/config.yaml
      template:
        src: "templates/config.yaml.j2"
        dest: /etc/foreman_scap_client/config.yaml

    - name: Running the OpenSCAP client policies
      command: "/usr/bin/foreman_scap_client {{ hostvars['localhost']['policy']['id'] }}"
